CREATE DATABASE Events;

CREATE TABLE Event(
  Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  Email VARCHAR(200) NOT NULL REFERENCES User(Email),
  Title VARCHAR(100) NOT NULL,
  Description VARCHAR(300) NOT NULL,
  StartTime TIME NOT NULL,
  EventDate VARCHAR(10) NOT NULL
);

CREATE TABLE User(
  Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Email VARCHAR(200) NOT NULL,
  Phone VARCHAR(12)
);